/**
 * 扩展词根库（雅思/学术词汇常见希腊拉丁词根）。
 * 合并入 ROOT_ETYMOLOGY。
 * @type {Record<string, { meaning: string, source: string, pie?: string }>}
 */
export const EXTENDED_ROOTS = {
  vide: { meaning: '看', source: 'Latin videre', pie: 'PIE *weid-' },
  vis: { meaning: '看', source: 'Latin videre', pie: 'PIE *weid-' },
  ploy: { meaning: '折、用', source: 'Latin implicare', pie: 'PIE *plek-「编」' },
  ploi: { meaning: '折', source: 'Latin plicare', pie: 'PIE *plek-' },
  rept: { meaning: '爬', source: 'Latin repere', pie: 'PIE *rep-' },
  dem: { meaning: '人民', source: 'Greek demos', pie: 'PIE *dā-「分」' },
  demo: { meaning: '人民', source: 'Greek demos', pie: 'PIE *dā-' },
  epidem: { meaning: '在人民中', source: 'Greek epidemia', pie: 'Greek epi + demos' },
  pan: { meaning: '全', source: 'Greek pan', pie: 'PIE *peh₂-' },
  pandem: { meaning: '全民', source: 'Greek pandemos', pie: 'Greek pan + demos' },
  organ: { meaning: '器官', source: 'Greek organon', pie: 'PIE *werg-「工作」' },
  org: { meaning: '器官', source: 'Greek organon', pie: 'PIE *werg-' },
  seism: { meaning: '震动', source: 'Greek seismos', pie: 'PIE *tweye-「震动」' },
  seismo: { meaning: '地震', source: 'Greek seismos', pie: 'PIE *tweye-' },
  chron: { meaning: '时间', source: 'Greek chronos', pie: 'PIE *sker-「切」' },
  lith: { meaning: '石', source: 'Greek lithos', pie: 'PIE *lei-「石头」' },
  astr: { meaning: '星', source: 'Greek astron', pie: 'PIE *h₂ster-' },
  astro: { meaning: '星', source: 'Greek astron', pie: 'PIE *h₂ster-' },
  cosm: { meaning: '宇宙', source: 'Greek kosmos', pie: 'PIE *ken-「整理」' },
  cosmo: { meaning: '宇宙', source: 'Greek kosmos', pie: 'PIE *ken-' },
  neur: { meaning: '神经', source: 'Greek neuron', pie: 'PIE *neur-' },
  neuro: { meaning: '神经', source: 'Greek neuron', pie: 'PIE *neur-' },
  onc: { meaning: '肿', source: 'Greek onkos', pie: 'Greek 专名' },
  onco: { meaning: '瘤', source: 'Greek onkos', pie: 'Greek 专名' },
  cardi: { meaning: '心', source: 'Greek kardia', pie: 'PIE *kerd-' },
  cardio: { meaning: '心', source: 'Greek kardia', pie: 'PIE *kerd-' },
  derm: { meaning: '皮', source: 'Greek derma', pie: 'PIE *der-「皮」' },
  derma: { meaning: '皮', source: 'Greek derma', pie: 'PIE *der-' },
  oste: { meaning: '骨', source: 'Greek osteon', pie: 'PIE *ost-' },
  osteo: { meaning: '骨', source: 'Greek osteon', pie: 'PIE *ost-' },
  hemat: { meaning: '血', source: 'Greek haima', pie: 'PIE *és-h₁r「血」' },
  hemo: { meaning: '血', source: 'Greek haima', pie: 'PIE *és-h₁r' },
  haem: { meaning: '血', source: 'Greek haima', pie: 'PIE *és-h₁r' },
  patho: { meaning: '病', source: 'Greek pathos', pie: 'PIE *kwent(h)-' },
  pharm: { meaning: '药', source: 'Greek pharmakon', pie: 'PIE *bher-「携带」' },
  pharmaco: { meaning: '药', source: 'Greek pharmakon', pie: 'PIE *bher-' },
  tox: { meaning: '毒', source: 'Greek toxon', pie: 'PIE *toxs-' },
  toxo: { meaning: '毒', source: 'Latin toxicum', pie: 'PIE *toxs-' },
  zo: { meaning: '动物', source: 'Greek zoon', pie: 'PIE *gʷeyh₁-' },
  zoo: { meaning: '动物', source: 'Greek zoon', pie: 'PIE *gʷeyh₁-' },
  zoon: { meaning: '动物', source: 'Greek zoon', pie: 'PIE *gʷeyh₁-' },
  botan: { meaning: '植物', source: 'Greek botane', pie: 'PIE *bhut-' },
  bot: { meaning: '植物', source: 'Greek botane', pie: 'PIE *bhut-' },
  agron: { meaning: '田', source: 'Greek agros', pie: 'PIE *ag-「驱」' },
  agr: { meaning: '田', source: 'Latin ager', pie: 'PIE *ag-' },
  litho: { meaning: '石', source: 'Greek lithos', pie: 'PIE *lei-' },
  petro: { meaning: '石', source: 'Greek petra', pie: 'PIE *per-' },
  metal: { meaning: '金属', source: 'Greek metallon', pie: 'PIE *mel-' },
  magnet: { meaning: '磁', source: 'Greek Magnesia', pie: '地名' },
  electr: { meaning: '电', source: 'Greek elektron', pie: 'Greek 专名' },
  electro: { meaning: '电', source: 'Greek elektron', pie: 'Greek 专名' },
  nucle: { meaning: '核', source: 'Latin nucleus', pie: 'PIE *knē-' },
  nucleo: { meaning: '核', source: 'Latin nucleus', pie: 'PIE *knē-' },
  atom: { meaning: '原子', source: 'Greek atomos', pie: 'PIE *tem-「切」' },
  molec: { meaning: '分子', source: 'Latin moles', pie: 'PIE *mel-' },
  ion: { meaning: '离子', source: 'Greek ion', pie: 'Greek 专名' },
  bar: { meaning: '重、压', source: 'Greek baros', pie: 'PIE *gʷer-' },
  baro: { meaning: '压', source: 'Greek baros', pie: 'PIE *gʷer-' },
  thermo: { meaning: '热', source: 'Greek thermos', pie: 'PIE *gʷher-' },
  cryo: { meaning: '冷', source: 'Greek kryos', pie: 'PIE *kreuh₂-' },
  hydr: { meaning: '水', source: 'Greek hydor', pie: 'PIE *wed-' },
  hydro: { meaning: '水', source: 'Greek hydor', pie: 'PIE *wed-' },
  oxy: { meaning: '氧', source: 'Greek oxys', pie: 'PIE *ak-「尖」' },
  carb: { meaning: '碳', source: 'Latin carbo', pie: '拉丁 carbo 系（非希腊 keramos）' },
  carbon: { meaning: '碳', source: 'Latin carbo', pie: '拉丁 carbo 系（非希腊 keramos）' },
  nitr: { meaning: '硝', source: 'Latin nitrum', pie: 'PIE *nei-' },
  sulph: { meaning: '硫', source: 'Latin sulfur', pie: 'PIE 借词' },
  sulfur: { meaning: '硫', source: 'Latin sulfur', pie: 'PIE 借词' },
  ferment: { meaning: '发酵', source: 'Latin fermentum', pie: 'PIE *bher-' },
  vuls: { meaning: '扯', source: 'Latin vellere', pie: 'PIE *wel-「撕」' },
  vul: { meaning: '扯', source: 'Latin vellere', pie: 'PIE *wel-' },
  puls: { meaning: '推', source: 'Latin pellere', pie: 'PIE *pel-' },
  pel: { meaning: '推', source: 'Latin pellere', pie: 'PIE *pel-' },
  cept: { meaning: '拿', source: 'Latin capere', pie: 'PIE *kap-' },
  ceive: { meaning: '取', source: 'Latin capere', pie: 'PIE *kap-' },
  ceiv: { meaning: '取', source: 'Latin capere', pie: 'PIE *kap-' },
  capt: { meaning: '拿', source: 'Latin capere', pie: 'PIE *kap-' },
  cap: { meaning: '头；抓', source: 'Latin caput / capere', pie: 'PIE *kap-' },
  cept: { meaning: '拿', source: 'Latin capere', pie: 'PIE *kap-' },
  bark: { meaning: '船', source: 'Old French barque', pie: 'Latin barca' },
  barque: { meaning: '船', source: 'Latin barca', pie: 'PIE 借词' },
  bark: { meaning: '船', source: 'Latin barca', pie: '借词' },
  vol: { meaning: '卷、意愿', source: 'Latin volvere / velle', pie: 'PIE *wel-' },
  volv: { meaning: '转', source: 'Latin volvere', pie: 'PIE *wel-' },
  volu: { meaning: '卷', source: 'Latin volvere', pie: 'PIE *wel-' },
  volut: { meaning: '卷', source: 'Latin volvere', pie: 'PIE *wel-' },
  prop: { meaning: '自己的', source: 'Latin proprius', pie: 'PIE *pro-' },
  propri: { meaning: '自己的', source: 'Latin proprius', pie: 'PIE *pro-' },
  pri: { meaning: '私有的', source: 'Latin privus', pie: 'PIE *per-' },
  ceiv: { meaning: '取', source: 'Latin capere', pie: 'PIE *kap-' },
  erty: { meaning: '性质', source: 'French -ité → -ty', pie: 'Latin -itas' },
  ceive: { meaning: '取', source: 'Latin capere', pie: 'PIE *kap-' },
  cept: { meaning: '拿', source: 'Latin capere', pie: 'PIE *kap-' },
  quir: { meaning: '求', source: 'Latin quaerere', pie: 'PIE *kwe-' },
  quest: { meaning: '求', source: 'Latin quaerere', pie: 'PIE *kwe-' },
  quir: { meaning: '问', source: 'Latin quaerere', pie: 'PIE *kwe-' },
  semin: { meaning: '种子', source: 'Latin semen', pie: 'PIE *seh₁-' },
  sem: { meaning: '种子', source: 'Latin semen', pie: 'PIE *seh₁-' },
  semen: { meaning: '种子', source: 'Latin semen', pie: 'PIE *seh₁-' },
  sperm: { meaning: '种子', source: 'Greek sperma', pie: 'PIE *sper-' },
  sperma: { meaning: '种子', source: 'Greek sperma', pie: 'PIE *sper-' },
  gam: { meaning: '婚姻', source: 'Greek gamos', pie: 'PIE *gem-' },
  gamet: { meaning: '配子', source: 'Greek gametes', pie: 'PIE *gem-' },
  embry: { meaning: '胚', source: 'Greek embryon', pie: 'PIE *bhreu-' },
  embryon: { meaning: '胚', source: 'Greek embryon', pie: 'PIE *bhreu-' },
  foet: { meaning: '胎', source: 'Latin fetus', pie: 'PIE *dʰeh₁-' },
  fetus: { meaning: '胎', source: 'Latin fetus', pie: 'PIE *dʰeh₁-' },
  fet: { meaning: '胎', source: 'Latin fetus', pie: 'PIE *dʰeh₁-' },
  mamm: { meaning: '乳', source: 'Latin mamma', pie: 'PIE *méh₂dʰr' },
  marsup: { meaning: '袋', source: 'Greek marsypion', pie: 'Greek 专名' },
  rept: { meaning: '爬', source: 'Latin repere', pie: 'PIE *rep-' },
  reptil: { meaning: '爬', source: 'Latin repere', pie: 'PIE *rep-' },
  amph: { meaning: '两侧', source: 'Greek amphi', pie: 'PIE *ambhi-' },
  amphibi: { meaning: '两栖', source: 'Greek amphi + bios', pie: 'PIE *ambhi- + *gwei-' },
  avi: { meaning: '鸟', source: 'Latin avis', pie: 'PIE *h₂ewi-' },
  ornith: { meaning: '鸟', source: 'Greek ornis', pie: 'PIE *h₂er-' },
  ichthy: { meaning: '鱼', source: 'Greek ichthys', pie: 'PIE *dhghū-' },
  entom: { meaning: '昆虫', source: 'Greek entomon', pie: 'PIE *ent-' },
  arachn: { meaning: '蛛', source: 'Greek arachne', pie: 'Greek 专名' },
  myri: { meaning: '万', source: 'Greek myrios', pie: 'PIE *meǵ-' },
  kilo: { meaning: '千', source: 'Greek khilioi', pie: 'PIE *ǵʰeslō-' },
  milli: { meaning: '千分之一', source: 'Latin mille', pie: 'PIE *gʷmel-' },
  centi: { meaning: '百', source: 'Latin centum', pie: 'PIE *ḱm̥tóm' },
  deci: { meaning: '十', source: 'Latin decem', pie: 'PIE *déḱm' },
  hecto: { meaning: '百', source: 'Greek hekaton', pie: 'PIE *ḱm̥tóm' },
  mega: { meaning: '大', source: 'Greek megas', pie: 'PIE *meg-' },
  giga: { meaning: '十亿', source: 'Greek gigas', pie: 'Greek 专名' },
  nano: { meaning: '纳', source: 'Latin nanus', pie: 'Greek nanos' },
  pico: { meaning: '皮', source: 'Spanish pico', pie: '现代单位' },
  circ: { meaning: '环', source: 'Latin circus', pie: 'PIE *sker-「弯」' },
  circu: { meaning: '环', source: 'Latin circulus', pie: 'PIE *sker-' },
  circuit: { meaning: '环', source: 'Latin circuire', pie: 'PIE *sker-' },
  cycl: { meaning: '圆', source: 'Greek kyklos', pie: 'PIE *kwel-「转」' },
  cyclo: { meaning: '圆', source: 'Greek kyklos', pie: 'PIE *kwel-' },
  orb: { meaning: '球', source: 'Latin orbis', pie: 'PIE *h₃rebʰ-' },
  spher: { meaning: '球', source: 'Greek sphaira', pie: 'PIE *spher-' },
  sphaer: { meaning: '球', source: 'Greek sphaira', pie: 'PIE *spher-' },
  angl: { meaning: '角', source: 'Latin angulus', pie: 'PIE *h₂eng-' },
  angul: { meaning: '角', source: 'Latin angulus', pie: 'PIE *h₂eng-' },
  rect: { meaning: '直', source: 'Latin regere', pie: 'PIE *h₃reg-' },
  quadr: { meaning: '四', source: 'Latin quattuor', pie: 'PIE *kʷetwóres' },
  quadri: { meaning: '四', source: 'Latin quattuor', pie: 'PIE *kʷetwóres' },
  pent: { meaning: '五', source: 'Greek pente', pie: 'PIE *pénkʷe' },
  hex: { meaning: '六', source: 'Greek hex', pie: 'PIE *sweḱs' },
  hept: { meaning: '七', source: 'Greek hepta', pie: 'PIE *septḿ̥' },
  oct: { meaning: '八', source: 'Latin octo', pie: 'PIE *h₃eḱtṓw' },
  dec: { meaning: '十', source: 'Latin decem', pie: 'PIE *déḱm' },
  decem: { meaning: '十', source: 'Latin decem', pie: 'PIE *déḱm' },
  undec: { meaning: '十一', source: 'Latin undecim', pie: 'PIE *oino- + *dekm' },
  arid: { meaning: '干', source: 'Latin aridus', pie: 'PIE *h₂eh₁s-「烧」' },
  ar: { meaning: '干', source: 'Latin arere', pie: 'PIE *h₂eh₁s-' },
  humid: { meaning: '湿', source: 'Latin humidus', pie: 'PIE *wegʷ-「湿」' },
  humid: { meaning: '湿', source: 'Latin humidus', pie: 'PIE *wegʷ-' },
  sicc: { meaning: '干', source: 'Latin siccus', pie: 'PIE *seyk-' },
  xer: { meaning: '干', source: 'Greek xeros', pie: 'PIE *ksē-' },
  xero: { meaning: '干', source: 'Greek xeros', pie: 'PIE *ksē-' },
  ign: { meaning: '火', source: 'Latin ignis', pie: 'PIE *h₁ngʷni-' },
  igni: { meaning: '火', source: 'Latin ignis', pie: 'PIE *h₁ngʷni-' },
  flamm: { meaning: '焰', source: 'Latin flamma', pie: 'PIE *bʰel-' },
  flagr: { meaning: '烧', source: 'Latin flagrare', pie: 'PIE *bʰleg-' },
  crem: { meaning: '焚', source: 'Latin cremare', pie: 'PIE *krem-' },
  ceram: { meaning: '陶', source: 'Greek keramos' },
  keram: { meaning: '陶', source: 'Greek keramos', pie: 'PIE *ker-' },
  porcel: { meaning: '瓷', source: 'Italian porcellana', pie: '意大利语' },
  ivory: { meaning: '象牙', source: 'Old French ivoire', pie: '埃及借词' },
  ivor: { meaning: '象牙', source: 'Latin ebur', pie: 'PIE *h₂egʷʰ-' },
  bronze: { meaning: '青铜', source: 'Italian bronzo', pie: '不确定' },
  brass: { meaning: '黄铜', source: 'Old English bræs', pie: '日耳曼' },
  rebuk: { meaning: '斥责', source: 'Old French rebuker', pie: '日耳曼' },
  confer: { meaning: '商议', source: 'Latin conferre', pie: 'PIE *bher-「携带」' },
  fer: { meaning: '携带', source: 'Latin ferre', pie: 'PIE *bher-「携带」' },
  lat: { meaning: '带来', source: 'Latin latus', pie: 'PIE *bher-' },
  phor: { meaning: '携带', source: 'Greek pherein', pie: 'PIE *bher-' },
  pher: { meaning: '携带', source: 'Greek pherein', pie: 'PIE *bher-' },
  gest: { meaning: '携带', source: 'Latin gerere', pie: 'PIE *bher-' },
  gist: { meaning: '携带', source: 'Latin gerere', pie: 'PIE *bher-' },
  pragm: { meaning: '做', source: 'Greek pragma', pie: 'PIE *per-「通过」' },
  prag: { meaning: '做', source: 'Greek prassein', pie: 'PIE *per-' },
  dogm: { meaning: '教条', source: 'Greek dokein', pie: 'PIE *dek-「接受」' },
  dog: { meaning: '意见', source: 'Greek doxa', pie: 'PIE *dek-' },
  the: { meaning: '放置', source: 'Greek tithenai', pie: 'PIE *dhe-「放」' },
  thes: { meaning: '放', source: 'Greek thesis', pie: 'PIE *dhe-' },
  thet: { meaning: '放', source: 'Greek thesis', pie: 'PIE *dhe-' },
  them: { meaning: '放置', source: 'Greek tithenai', pie: 'PIE *dhe-' },
  thetic: { meaning: '放置', source: 'Greek thesis', pie: 'PIE *dhe-' },
  est: { meaning: '是', source: 'Latin esse', pie: 'PIE *h₁es-' },
  esteem: { meaning: '估价', source: 'Latin aestimare', pie: 'PIE *h₂ey-' },
  aestim: { meaning: '估价', source: 'Latin aestimare', pie: 'PIE *h₂ey-' },
  estim: { meaning: '估价', source: 'Latin aestimare', pie: 'PIE *h₂ey-' },
  imput: { meaning: '归罪', source: 'Latin imputare', pie: 'PIE *put-「思考」' },
  put: { meaning: '思考', source: 'Latin putare', pie: 'PIE *put-' },
  comput: { meaning: '计算', source: 'Latin computare', pie: 'PIE *put-' },
  disput: { meaning: '争论', source: 'Latin disputare', pie: 'PIE *put-' },
  reput: { meaning: '名誉', source: 'Latin reputare', pie: 'PIE *put-' },
  account: { meaning: '账目', source: 'Latin computare', pie: 'PIE *put-' },
  count: { meaning: '数', source: 'Latin computare', pie: 'PIE *put-' },
  caus: { meaning: '原因', source: 'Latin causa', pie: 'PIE *kʷeh₂-' },
  causa: { meaning: '原因', source: 'Latin causa', pie: 'PIE *kʷeh₂-' },
  effect: { meaning: '做', source: 'Latin efficere', pie: 'PIE *dhe-' },
  infect: { meaning: '做', source: 'Latin inficere', pie: 'PIE *dhe-' },
  defect: { meaning: '做', source: 'Latin deficere', pie: 'PIE *dhe-' },
  perfect: { meaning: '做', source: 'Latin perficere', pie: 'PIE *dhe-' },
  infect: { meaning: '做', source: 'Latin inficere', pie: 'PIE *dhe-' },
  pragmat: { meaning: '做', source: 'Greek pragma', pie: 'PIE *per-' },
  endow: { meaning: '捐赠', source: 'Anglo-French endower', pie: 'PIE *deu-' },
  dow: { meaning: '嫁奁', source: 'Latin dos', pie: 'PIE *deu-' },
  don: { meaning: '给', source: 'Latin donare', pie: 'PIE *deh₃-' },
  dot: { meaning: '给', source: 'Latin dotare', pie: 'PIE *deh₃-' },
  predator: { meaning: '掠食', source: 'Latin praedari', pie: 'PIE *gʰed-' },
  praed: { meaning: '掠食', source: 'Latin praeda', pie: 'PIE *gʰed-' },
  prey: { meaning: '猎物', source: 'Latin praeda', pie: 'PIE *gʰed-' },
  domestic: { meaning: '家', source: 'Latin domesticus', pie: 'PIE *dem-「家」' },
  dom: { meaning: '家', source: 'Latin domus', pie: 'PIE *dem-' },
  domo: { meaning: '家', source: 'Latin domus', pie: 'PIE *dem-' },
  employ: { meaning: '用', source: 'Latin implicare', pie: 'PIE *plek-「折」' },
  ploy: { meaning: '折', source: 'Latin implicare', pie: 'PIE *plek-' },
  adopt: { meaning: '选', source: 'Latin adoptare', pie: 'PIE *op- + *kap-' },
  opt: { meaning: '选', source: 'Latin optare', pie: 'PIE *op-' },
  ad: { meaning: '向', source: 'Latin ad', pie: 'PIE *ad-' },
  undergo: { meaning: '经历', source: 'Old English undergan', pie: '日耳曼' },
  undergo: { meaning: '经历', source: 'Germanic under + go', pie: '日耳曼' },
  undergo: { meaning: '下', source: 'Germanic', pie: '日耳曼' },
  disdain: { meaning: '鄙视', source: 'Old French desdeignier', pie: 'Latin dignus' },
  dign: { meaning: '尊严', source: 'Latin dignus', pie: 'PIE *dek-「接受」' },
  taper: { meaning: '锥', source: 'Old English tapor', pie: '日耳曼' },
  amass: { meaning: '积累', source: 'French amasser', pie: 'Latin massa' },
  mass: { meaning: '团', source: 'Latin massa', pie: 'Greek maza' },
  dwindle: { meaning: '减少', source: 'Old English dwīnan', pie: '日耳曼' },
  churn: { meaning: '搅动', source: 'Old English cyrin', pie: '日耳曼' },
  mesh: { meaning: '网', source: 'Old English masc', pie: '日耳曼' },
  strike: { meaning: '打', source: 'Old English strīcan', pie: '日耳曼' },
  lay: { meaning: '放', source: 'Old English lecgan', pie: 'PIE *legh-' },
  wipe: { meaning: '擦', source: 'Old English wīpian', pie: '日耳曼' },
  split: { meaning: '裂', source: 'Middle Dutch splitten', pie: '日耳曼' },
  stem: { meaning: '茎', source: 'Old English stemn', pie: '日耳曼' },
  hub: { meaning: '毂', source: 'Unknown', pie: '不确定' },
  recipe: { meaning: '取', source: 'Latin recipe', pie: 'PIE *kap-' },
  rag: { meaning: '破布', source: 'Unknown', pie: '不确定' },
  barren: { meaning: '贫瘠', source: 'Old French baraigne', pie: '日耳曼' },
  barb: { meaning: '倒钩', source: 'Latin barba', pie: 'PIE *bhardh-' },
  chest: { meaning: '胸', source: 'Old English cest', pie: 'PIE *kist-' },
  exotic: { meaning: '外来', source: 'Greek exotikos', pie: 'PIE *eks-「外」' },
  pest: { meaning: '瘟疫', source: 'Latin pestis', pie: 'PIE *pes-' },
  carcass: { meaning: '尸体', source: 'Old French carcois', pie: '法语' },
  precast: { meaning: '预制', source: 'Modern English pre + cast', pie: '现代合成' },
  cast: { meaning: '投', source: 'Old Norse kasta', pie: '日耳曼' },
  worsted: { meaning: '呢', source: 'Worstead 地名', pie: '地名' },
  sought: { meaning: '寻求', source: 'Old English secan', pie: '日耳曼' },
  arable: { meaning: '可耕', source: 'Latin arare', pie: 'PIE *h₂erh₃-「犁」' },
  ar: { meaning: '犁', source: 'Latin arare', pie: 'PIE *h₂erh₃-' },
  ara: { meaning: '犁', source: 'Latin arare', pie: 'PIE *h₂erh₃-' },
  cult: { meaning: '耕', source: 'Latin colere', pie: 'PIE *kwel-' },
  col: { meaning: '耕', source: 'Latin colere', pie: 'PIE *kwel-' },
  empowerment: { meaning: '权', source: 'Modern power + -ment', pie: '现代' },
  power: { meaning: '力', source: 'Latin posse', pie: 'PIE *poti-' },
  subtle: { meaning: '编织', source: 'Latin subtilis', pie: 'PIE *teks-「织」' },
  til: { meaning: '细', source: 'Latin subtilis', pie: 'PIE *teks-' },
  tle: { meaning: '编织', source: 'Latin tela', pie: 'PIE *teks-' },
  tex: { meaning: '织', source: 'Latin texere', pie: 'PIE *teks-' },
  text: { meaning: '织', source: 'Latin texere', pie: 'PIE *teks-' },
  tiss: { meaning: '织', source: 'Latin texere', pie: 'PIE *teks-' },
  tissue: { meaning: '织', source: 'Latin texere', pie: 'PIE *teks-' },
  context: { meaning: '织', source: 'Latin texere', pie: 'PIE *teks-' },
  pretext: { meaning: '织', source: 'Latin texere', pie: 'PIE *teks-' },
  texture: { meaning: '织', source: 'Latin texere', pie: 'PIE *teks-' },
  textile: { meaning: '织', source: 'Latin texere', pie: 'PIE *teks-' },
  technical: { meaning: '技', source: 'Greek techne', pie: 'PIE *teks-' },
  techn: { meaning: '技', source: 'Greek techne', pie: 'PIE *teks-' },
  tech: { meaning: '技', source: 'Greek techne', pie: 'PIE *teks-' },
  architect: { meaning: '建', source: 'Greek arkhi + tekton', pie: 'PIE *teks-' },
  tekton: { meaning: '工匠', source: 'Greek tekton', pie: 'PIE *teks-' },
  tek: { meaning: '工', source: 'Greek tekton', pie: 'PIE *teks-' },
}
