/**
 * 日耳曼本土词（无拉丁/希腊前后缀，作为单一词根语素 + PIE/古英语来源）。
 * @type {Record<string, { meaning: string, source: string, pie?: string }>}
 */
export const GERMANIC_LEXICON = {
  take: { meaning: '拿、取', source: 'Old English tacan', pie: 'PIE *deh₃-「放」' },
  make: { meaning: '制作', source: 'Old English macian', pie: 'PIE *mag-「揉、塑」' },
  get: { meaning: '获得', source: 'Old Norse geta / OE gietan', pie: 'PIE *gʰed-' },
  give: { meaning: '给', source: 'Old English giefan', pie: 'PIE *gʰebʰ-' },
  go: { meaning: '去', source: 'Old English gān', pie: 'PIE *gʰeh₁-' },
  come: { meaning: '来', source: 'Old English cuman', pie: 'PIE *gʷem-' },
  see: { meaning: '看', source: 'Old English sēon', pie: 'PIE *sekʷ-' },
  say: { meaning: '说', source: 'Old English secgan', pie: 'PIE *sekʷ-' },
  tell: { meaning: '告诉', source: 'Old English tellan', pie: 'PIE *telh₂-' },
  think: { meaning: '想', source: 'Old English þencan', pie: 'PIE *tenk-' },
  know: { meaning: '知', source: 'Old English cnawan', pie: 'PIE *ǵneh₃-' },
  find: { meaning: '发现', source: 'Old English findan', pie: 'PIE *pent-' },
  turn: { meaning: '转', source: 'Old English turnian', pie: 'Latin tornare → English' },
  strike: { meaning: '打', source: 'Old English strīcan', pie: 'PIE *streyg-' },
  break: { meaning: '破', source: 'Old English brecan', pie: 'PIE *bhreg-' },
  lay: { meaning: '放', source: 'Old English lecgan', pie: 'PIE *legh-' },
  wipe: { meaning: '擦', source: 'Old English wīpian', pie: '日耳曼本土' },
  split: { meaning: '裂', source: 'Middle Dutch splitten', pie: '日耳曼本土' },
  stem: { meaning: '茎', source: 'Old English stemn', pie: '日耳曼本土' },
  pick: { meaning: '挑', source: 'Middle English picken', pie: '日耳曼本土' },
  carry: { meaning: '携带', source: 'Old French carrier / Latin carrus', pie: 'PIE *kers-' },
  mesh: { meaning: '网', source: 'Old English masc', pie: '日耳曼本土' },
  churn: { meaning: '搅', source: 'Old English cyrin', pie: '日耳曼本土' },
  yet: { meaning: '尚', source: 'Old English gīet', pie: '日耳曼本土' },
  be: { meaning: '是', source: 'Old English bēon', pie: 'PIE *h₁es-' },
  has: { meaning: '有', source: 'Old English habban', pie: 'PIE *keh₂p-' },
  had: { meaning: '有', source: 'Old English habban', pie: 'PIE *keh₂p-' },
  do: { meaning: '做', source: 'Old English dōn', pie: 'PIE *dʰeh₁-' },
  did: { meaning: '做', source: 'Old English dōn', pie: 'PIE *dʰeh₁-' },
  draw: { meaning: '拉', source: 'Old English dragan', pie: 'PIE *dʰreg-' },
  drive: { meaning: '驱', source: 'Old English drīfan', pie: 'PIE *dʰreibʰ-' },
  eat: { meaning: '吃', source: 'Old English etan', pie: 'PIE *h₁ed-' },
  fall: { meaning: '落', source: 'Old English feallan', pie: 'PIE *polH-' },
  feel: { meaning: '感', source: 'Old English fēlan', pie: 'PIE *palh₁-' },
  fight: { meaning: '战', source: 'Old English feohtan', pie: 'PIE *pewk-' },
  hold: { meaning: '持', source: 'Old English healdan', pie: 'PIE *kel-' },
  keep: { meaning: '保', source: 'Old English cēpan', pie: 'PIE *kāp-' },
  lead: { meaning: '引', source: 'Old English lǣdan', pie: 'PIE *leit-' },
  leave: { meaning: '离', source: 'Old English lǣfan', pie: 'PIE *leyp-' },
  lend: { meaning: '借', source: 'Old English lǣnan', pie: '日耳曼本土' },
  let: { meaning: '让', source: 'Old English lettan', pie: '日耳曼本土' },
  lie: { meaning: '躺', source: 'Old English licgan', pie: 'PIE *legʰ-' },
  lose: { meaning: '失', source: 'Old English losian', pie: 'PIE *leus-' },
  mean: { meaning: '意指', source: 'Old English mænan', pie: 'PIE *meyn-' },
  meet: { meaning: '遇', source: 'Old English metan', pie: 'PIE *mod-' },
  pay: { meaning: '付', source: 'Old French payer', pie: 'PIE *pey-' },
  put: { meaning: '放', source: 'Old English putian', pie: '不确定' },
  read: { meaning: '读', source: 'Old English rǣdan', pie: 'PIE *h₃reh₁-' },
  ride: { meaning: '骑', source: 'Old English rīdan', pie: 'PIE *reidh-' },
  rise: { meaning: '升', source: 'Old English rīsan', pie: 'PIE *h₁rei-' },
  run: { meaning: '跑', source: 'Old English rinnan', pie: 'PIE *h₃er-' },
  seek: { meaning: '寻', source: 'Old English sēcan', pie: 'PIE *seh₂g-' },
  sell: { meaning: '卖', source: 'Old English sellan', pie: 'PIE *selh₃-' },
  send: { meaning: '送', source: 'Old English sendan', pie: 'PIE *sent-' },
  set: { meaning: '置', source: 'Old English settan', pie: 'PIE *sod-' },
  shake: { meaning: '摇', source: 'Old English sceacan', pie: 'PIE *skeg-' },
  shine: { meaning: '照', source: 'Old English scīnan', pie: 'PIE *skey-' },
  shoot: { meaning: '射', source: 'Old English scēotan', pie: 'PIE *skeud-' },
  show: { meaning: '示', source: 'Old English scēawian', pie: '日耳曼本土' },
  shut: { meaning: '关', source: 'Old English scyttan', pie: '日耳曼本土' },
  sing: { meaning: '唱', source: 'Old English singan', pie: 'PIE *sengʷ-' },
  sit: { meaning: '坐', source: 'Old English sittan', pie: 'PIE *sed-' },
  sleep: { meaning: '睡', source: 'Old English slǣpan', pie: 'PIE *sleh₂p-' },
  speak: { meaning: '说', source: 'Old English specan', pie: 'PIE *spreg-' },
  spend: { meaning: '花', source: 'Latin expendere → English', pie: 'PIE *pend-' },
  stand: { meaning: '站', source: 'Old English standan', pie: 'PIE *steh₂-' },
  stay: { meaning: '留', source: 'Old French ester', pie: 'PIE *steh₂-' },
  steal: { meaning: '偷', source: 'Old English stelan', pie: 'PIE *stel-' },
  stick: { meaning: '粘', source: 'Old English stician', pie: 'PIE *steyg-' },
  swim: { meaning: '游', source: 'Old English swimman', pie: 'PIE *swem-' },
  teach: { meaning: '教', source: 'Old English tǣcan', pie: 'PIE *deyk-' },
  tear: { meaning: '撕', source: 'Old English teran', pie: 'PIE *der-' },
  throw: { meaning: '扔', source: 'Old English þrāwan', pie: 'PIE *terh₁-' },
  tie: { meaning: '系', source: 'Old English tīgan', pie: 'PIE *deyḱ-' },
  wear: { meaning: '穿', source: 'Old English werian', pie: 'PIE *wes-' },
  win: { meaning: '赢', source: 'Old English winnan', pie: 'PIE *h₂wey-' },
  write: { meaning: '写', source: 'Old English wrītan', pie: 'PIE *wreyt-' },
  account: { meaning: '账目', source: 'Latin computare → English', pie: 'PIE *put-' },
  cause: { meaning: '原因', source: 'Latin causa', pie: 'PIE *kʷeh₂-' },
  mass: { meaning: '团', source: 'Latin massa', pie: 'Greek maza' },
  correctly: { meaning: '正确地', source: 'Latin correctus + -ly', pie: 'PIE *reg-' },
  hub: { meaning: '毂', source: 'Unknown', pie: '不确定' },
  rag: { meaning: '破布', source: 'Unknown', pie: '不确定' },
  cot: { meaning: '床', source: 'Hindi khat', pie: '借词' },
  giving: { meaning: '给予', source: 'give + -ing', pie: 'PIE *gʰebʰ-' },
  sought: { meaning: '寻求', source: 'Old English secan', pie: 'PIE *seh₂g-' },
  tsunami: { meaning: '海啸', source: 'Japanese 津波', pie: '日语借词（整词）' },
  correctly: { meaning: '正确地', source: 'correct + -ly', pie: 'PIE *reg-' },
}
